### ISSUE TITLE
my config syntex is corect?

### ISSUE THREAD

**Issue by rursi** [andrew7x11/subcord#2]
webhook = https://discord.com/api/webhooks/818828599649xxxxxxxxxsecret
mention = 574681422778990603
channels = UCocvwThNlcQ8pdRFnXgpGbw
channels = UCl6Czb3nTpO2Xeqh9T6ARNA
channels = UCMM2GtjB3dIYehLd3veGKQQ
channels = UCOZX-LkzCS8OFQXo4D6y_gw
channels = UCvP7-gW-f2bfP4AXwSCBIMg
channels = UC8QOXu4R4qkbn-YkdaL520A
channels = UCIpYjbywLIlWE4vV_rdqFPw
channels = UC3mvE1cYqIEk_xETajsryNA
channels = UCbehzEsII2SDFIMrWvIdFmA
channels = UCOyKtXwAm6ALJ1-r3nugR5Q
channels = UCLDZPcoEW13GZgyOMsteQ1g
channels = UCyHvZz45Vn66nhmv4vRLtcA

**Comment by andrew7x11** [comment]
The variable names should not be there, they are implied by which line they are on. So:
```
https://discord.com/api/webhooks/818828599649xxxxxxxxxsecret
574681422778990603
UCocvwThNlcQ8pdRFnXgpGbw
```
Etc.
